kubeProxyReplacement: true
k8sServiceHost: 192.168.56.100
k8sServicePort: 6443
gatewayAPI:
  enabled: true
l2announcements:
  enabled: true
devices: eth1
externalIPs:
  enabled: true
encryption:
  enabled: true
  type: wireguard
  nodeEncryption: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enabled: {dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}
    enableOpenMetrics: true
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true