apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv
  namespace: robot-shop
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/redis-data