apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  chart:
    spec:
      chart: hashicorp/vault
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: flux-system
      version: 0.28.1
  install:
    createNamespace: false
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 1m0s
  releaseName: vault
  targetNamespace: kube-system
  values:
    server:
      affinity: ""
      ha:
        enabled: true
        raft:
          enabled: true
          setNodeId: true
          config: |
            cluster_name = "vault-integrated-storage"
            storage "raft" {
               path    = "/vault/data/"
            }
            
            listener "tcp" {
               address = "[::]:8200"
               cluster_address = "[::]:8201"
               tls_disable = "true"
            }
            service_registration "kubernetes" {}