apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    service: mysql
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mysql
  template:
    metadata:
      labels:
        service: mysql
        app.kubernetes.io/name: mysql
    spec:
      containers:
        - name: mysql
          image: robotshop/rs-mysql-db:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: 200m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 700Mi
      restartPolicy: Always