---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: flux-system
spec:
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: ./infrastructure/coredns-k8s-gateway
      sourceRef:
        kind: GitRepository
        name: flux-system
      interval: 1m
  releaseName: exdns
  install:
    remediation:
      retries: 3
  targetNamespace: kube-system
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled