apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
  labels:
    service: dispatch
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dispatch
  template:
    metadata:
      labels:
        service: dispatch
        app.kubernetes.io/name: dispatch
    spec:
      containers:
        - name: dispatch
          image: robotshop/rs-dispatch:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
      restartPolicy: Always