apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  chart:
    spec:
      chart: grafana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 8.3.4
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 1m0s
  releaseName: grafana
  targetNamespace: monitoring
  values:
    persistence:
      enabled: true
    ingress:
      enabled: true
    service:
      type: LoadBalancer
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        provider:
          disableDelete: true
          allowUiUpdates: false
          foldersFromFilesStructure: true
          folderAnnotation: grafana_dashboard_folder
