apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 61.3.2
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 1m0s
  releaseName: prometheus
  targetNamespace: monitoring
  values:
    fullnameOverride: prometheus
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false

        enableRemoteWriteReceiver: true
        enableFeatures:
          - exemplar-storage
      ingress:
        enabled: true
        hosts:
          - prometheus.example.com
      service:
        type: LoadBalancer

    alertmanager:
      enabled: false

    grafana:
      enabled: true
      serviceMonitor:
        enabled: true
      ingress:
        enabled: true
        hosts:
          - grafana.example.com

      persistence:
        enabled: false

      adminUser: admin
      adminPassword: password

      sidecar:
        dashboards:
          folderAnnotation: grafana_folder
          provider:
            foldersFromFilesStructure: true
    nodeExporter:
      enabled: false
    kubelet:
      enabled: false
    kubeStateMetrics:
      enabled: false


#prometheus.networkPolicy.enabled
#prometheus.networkPolicy.flavor   "cilium"