apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /wordpress-mysql/mysql/data
  claimRef:
    namespace: wordpress
    name: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-2
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /wordpress-mysql/wordpress/data
  claimRef:
    namespace: wordpress
    name: wp-pv-claim